CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE weather_history (
  id INT NOT NULL AUTO_INCREMENT,
  city_name VARCHAR(255) NOT NULL,
  user_id INT NOT NULL,
  coord_lon FLOAT NOT NULL,
  coord_lat FLOAT NOT NULL,
  weather_id INT NOT NULL,
  weather_main VARCHAR(255) NOT NULL,
  weather_description VARCHAR(255) NOT NULL,
  weather_icon VARCHAR(255) NOT NULL,
  base VARCHAR(255) NOT NULL,
  temp FLOAT NOT NULL,
  feels_like FLOAT NOT NULL,
  temp_min FLOAT NOT NULL,
  temp_max FLOAT NOT NULL,
  pressure INT NOT NULL,
  humidity INT NOT NULL,
  visibility INT NOT NULL,
  wind_speed FLOAT NOT NULL,
  wind_deg INT NOT NULL,
  clouds_all INT NOT NULL,
  dt INT NOT NULL,
  sys_type INT NOT NULL,
  sys_id INT NOT NULL,
  sys_country VARCHAR(255) NOT NULL,
  sys_sunrise INT NOT NULL,
  sys_sunset INT NOT NULL,
  timezone INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
